# Generated by Django 4.2.13 on 2024-07-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
