# Generated by Django 4.2.13 on 2024-07-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
